"use client";
import {useState} from "react";
const eur=(c:number)=>c.toLocaleString("de-DE",{style:"currency",currency:"EUR"});
export default function Admin({initialProducts,initialOrders}:{initialProducts:any[];initialOrders:any[]}){
const [products,setProducts]=useState(initialProducts),[orders,setOrders]=useState(initialOrders);
const [form,setForm]=useState({name:"",sku:"",description:"",priceCents:10400,securityLevel:2});
async function add(){const r=await fetch("/api/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(r.ok)location.reload();else alert((await r.json()).error)}
async function status(id:number,status:string){await fetch("/api/admin/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});setOrders(o=>o.map(x=>x.id===id?{...x,status}:x))}
async function remove(id:number){if(!confirm("Produkt wirklich löschen?"))return;const r=await fetch("/api/admin/products?id="+id,{method:"DELETE"});if(r.ok)setProducts(p=>p.filter(x=>x.id!==id));else alert((await r.json()).error)}

return <main><header><div className="nav wrap"><a className="logo" href="/">🔒 SCHLIESSANLAGEN<span>SHOP24</span></a><b>ADMIN</b></div></header><div className="wrap admin"><h1>Produktverwaltung & Bestellungen</h1><section className="adminbox"><h2>Produkt anlegen</h2><div className="form">{["name","sku","description"].map(k=><label key={k}>{k}<input value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Preis in Cent<input type="number" value={form.priceCents} onChange={e=>setForm({...form,priceCents:+e.target.value})}/></label><button className="btn gold" onClick={add}>Produkt speichern</button></div></section><section className="adminbox"><h2>Produkte</h2><div className="table"><table><thead><tr><th>ID</th><th>Name</th><th>SKU</th><th>Preis</th><th>Status</th><th>Löschen</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.id}</td><td>{p.name}</td><td>{p.sku}</td><td>{eur(p.price_cents)}</td><td>{p.active?"Aktiv":"Inaktiv"}</td><td><button className="btn light" onClick={()=>remove(p.id)}>Löschen</button></td></tr>)}</tbody></table></div></section><section className="adminbox"><h2>Bestellungen</h2><div className="table"><table><thead><tr><th>Nr.</th><th>Kunde</th><th>E-Mail</th><th>Summe</th><th>Status</th><th>Ändern</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.order_number}</td><td>{o.customer_name}</td><td>{o.email}</td><td>{eur(o.total_cents)}</td><td>{o.status}</td><td><select value={o.status} onChange={e=>status(o.id,e.target.value)}>
{["new","confirmed","production","shipped","completed","cancelled"].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div></section></div></main>
}
